version: "2"

services:

  mysql:
      image: mysql:5.6.26
      environment:
      - MYSQL_ROOT_PASSWORD=Popcan123
      - MYSQL_DATABASE=xPrincipia
      ports:
          - "4000:3306"

  api:
    # based off the golang:1.6.1-alpine image

    # #Docker hub image
    # image: xprincipia/backend

    # Local host build
    build:
      context: .

      dockerfile: dockerfile
    ports:
      - 10000:10000
    links: 
      - mysql
