version: "2"

services:
  api:
    # image: golang:1.6.1-alpine
    build:
      context: .
      dockerfile: Dockerfile
    # command: go get github.com/golang/glog
    # command: go get github.com/go-sql-driver/mysql
    # command: go get github.com/jinzhu/gorm 
    # command: go get github.com/joho/godotenv 
    # command: go get golang.org/x/crypto/bcrypt
    # command: go get gopkg.in/appleboy/gin-jwt.v2
    # command: go get gopkg.in/gin-gonic/gin.v1
    ports:
      - 10000:10000
    # working_dir: /go/src/work/xPrincipia/backend
    # command: go run server.go
    links:
      - mysql
  
  mysql:
    image: mysql:5.6.26
    environment:
    - MYSQL_ROOT_PASSWORD=Popcan123
    - MYSQL_DATABASE=xPrincipia
    ports:
        - "3300:3306"