version: "2"

services:

  mysql:
      image: mysql:5.6.26
      environment:
      - MYSQL_ROOT_PASSWORD=Popcan123
      - MYSQL_DATABASE=xPrincipia
      ports:
          - "4000:3306"

  api:
    # image: golang:1.6.1-alpine
    build:
      context: .
      
      dockerfile: Dockerfile
    ports:
      - 10000:10000
    # working_dir: /go/src/work/xPrincipia/backend
    # command: go run server.go
    links: 
      - mysql


    
  
  